<!DOCTYPE html>
<html lang="es">
	<head>
		<meta charset=<?= APP_CHARSET ?> >
		<title>KumbiaPHP Framework</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<?php Tag::css('kumbia.min') ?>
		<?= Html::includeCss() ?>
	</head>
	<body>
		<main>
			<article class="grid">
				<form>
					<header>
						<h1><?=_('Sign in')?></h1>
						<h2><?=_('Only for admins')?></h2>
					</header>
					<section>
						<input type="text" name="login" placeholder="Login" aria-label="Login" autocomplete="nickname" required>
						<input type="password" name="password" placeholder="Password" aria-label="Password" autocomplete="current-password" required>
						<label for="remember">
							<input type="checkbox" role="switch" id="remember" name="remember" aria-checked="false">
							<?=_('Remember me')?>
						</label>
					</section>
					<footer>
						<button type="submit" class="contrast"><?=_('Login')?></button>
					</footer>
				</form>
				<img alt="<?=_('Login img')?>" src="https://source.unsplash.com/random">
			</article>
		</main>
	</body>
</html>